# Generated by Django 4.0.1 on 2022-01-13 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CardG', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('Sell', 'Sell'), ('Buy', 'Buy')], max_length=5)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CardG.card')),
            ],
        ),
    ]
