# Generated by Django 4.0.1 on 2022-01-13 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2550)),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2550)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField()),
                ('name', models.CharField(max_length=2550)),
                ('desc', models.CharField(max_length=2550, null=True)),
                ('card_atk', models.IntegerField(blank=True, null=True)),
                ('card_def', models.IntegerField(blank=True, null=True)),
                ('card_level', models.IntegerField(blank=True, null=True)),
                ('archetype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CardG.archetype')),
                ('attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CardG.attribute')),
            ],
        ),
        migrations.CreateModel(
            name='Cardset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(max_length=2550)),
                ('set_code', models.CharField(max_length=2550)),
                ('set_rarity', models.CharField(max_length=2550)),
                ('set_rarity_code', models.CharField(max_length=2550)),
                ('set_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField()),
                ('image_url', models.URLField()),
                ('image_url_small', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2550)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2550)),
            ],
        ),
        migrations.CreateModel(
            name='CardPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardmarket_price', models.FloatField()),
                ('tcgplayer_price', models.FloatField()),
                ('ebay_price', models.FloatField()),
                ('amazon_price', models.FloatField()),
                ('coolstuffinc_price', models.FloatField()),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CardG.card')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='cardset',
            field=models.ManyToManyField(blank=True, to='CardG.Cardset'),
        ),
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CardG.image'),
        ),
        migrations.AddField(
            model_name='card',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CardG.race'),
        ),
        migrations.AddField(
            model_name='card',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CardG.type'),
        ),
    ]
