from secrets import token_hex
import os

SECRET_KEY = os.environ.get('SECRET_KEY') or token_hex(16)
SQLALCHEMY_TRACK_MODIFICATIONS = os.environ.get('SQLALCHEMY_TRACK_MODIFICATIONS')
SQLALCHEMY_DATABASE_URI = os.environ.get('DATABASE_URL') or 'postgresql://postgres:MAKAMLOVE1@localhost:5432/'
SQLALCHEMY_TRACK_MODIFICATIONS = False
MAIL_SERVER= 'smtp.googlemail.com'
MAIL_PORT = 5000
MAIL_USE_TLS = True
MAIL_USERNAME = os.environ.get('MAIL_USERNAME')
MAIL_PASSWORD = os.environ.get('MAIL_PASSWORD')
MAIL_SUBJECT_PREFIX = 'My Daily : '
MAIL_DEFAULT_SENDER = 'DevSquad From My Daily'
DROPZONE_DEFAULT_MESSAGE = 'Drop or Click to upload <br> (max 3 files can be uploaded)'
DROPZONE_ALLOWED_FILE_TYPE='image'
DROPZONE_MAX_FILE_SIZE=5
DROPZONE_MAX_FILES=3
DROPZONE_UPLOAD_ON_CLICK=True
DROPZONE_IN_FORM=True
DROPZONE_ENABLE_CSRF=True
DROPZONE_UPLOAD_MULTIPLE=True
DROPZONE_PARALLEL_UPLOADS=3
DROPZONE_UPLOAD_BTN_ID='submit'
DROPZONE_UPLOAD_ACTION='post.upload_image'
